# Generated by Django 4.2.7 on 2024-02-25 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0033_user_last_login_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="badge",
                        serialize=False,
                        to="user.user",
                    ),
                ),
                ("attendance_count", models.PositiveIntegerField(default=0)),
                (
                    "friendship_level",
                    models.IntegerField(
                        choices=[
                            (0, "Level default"),
                            (1, "Level 1"),
                            (2, "Level 2"),
                            (3, "Level 3"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "team_participance_level",
                    models.IntegerField(
                        choices=[
                            (0, "Level default"),
                            (1, "Level 1"),
                            (2, "Level 2"),
                            (3, "Level 3"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "team_post_level",
                    models.IntegerField(
                        choices=[
                            (0, "Level default"),
                            (1, "Level 1"),
                            (2, "Level 2"),
                            (3, "Level 3"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "liked_level",
                    models.IntegerField(
                        choices=[
                            (0, "Level default"),
                            (1, "Level 1"),
                            (2, "Level 2"),
                            (3, "Level 3"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "recruit_level",
                    models.IntegerField(
                        choices=[
                            (0, "Level default"),
                            (1, "Level 1"),
                            (2, "Level 2"),
                            (3, "Level 3"),
                        ],
                        default=0,
                    ),
                ),
                ("team_refusal_status", models.BooleanField(default=False)),
                ("user_profile_status", models.BooleanField(default=False)),
                ("team_leader_status", models.BooleanField(default=False)),
            ],
        ),
    ]
