# Generated by Django 4.2.7 on 2024-02-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badge", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="badge",
            old_name="attendance_count",
            new_name="attendance_cnt",
        ),
        migrations.AddField(
            model_name="badge",
            name="shared_profile_cnt",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
