# Generated by Django 4.2.7 on 2024-03-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badge", "0002_rename_attendance_count_badge_attendance_cnt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="review_status",
            field=models.BooleanField(default=False),
        ),
    ]
