# Generated by Django 4.2.7 on 2024-03-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badge", "0004_remove_badge_recruit_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badge",
            name="shared_profile_cnt",
        ),
        migrations.AddField(
            model_name="badge",
            name="shared_profile_status",
            field=models.BooleanField(default=False),
        ),
    ]
