# Generated by Django 4.2.7 on 2024-06-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("badge", "0006_badge_attendance_change_badge_friendship_change_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="badge",
            old_name="review_change",
            new_name="early_user_change",
        ),
        migrations.RenameField(
            model_name="badge",
            old_name="review_status",
            new_name="early_user_status",
        ),
    ]
