# Generated by Django 4.2.7 on 2024-06-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badge", "0007_rename_review_change_badge_early_user_change_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnt", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
