# Generated by Django 4.2.7 on 2024-06-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badge", "0008_usercount"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="attendance_level",
            field=models.IntegerField(
                choices=[
                    (0, "Level default"),
                    (1, "Level 1"),
                    (2, "Level 2"),
                    (3, "Level 3"),
                ],
                default=0,
            ),
        ),
    ]
