# Generated by Django 4.2.7 on 2024-06-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badge", "0009_badge_attendance_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="user_review_change",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="badge",
            name="user_review_cnt",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
