# Generated by Django 4.2.7 on 2024-06-13 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("badge", "0010_badge_user_review_change_badge_user_review_cnt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badge",
            name="friendship_change",
        ),
        migrations.RemoveField(
            model_name="badge",
            name="friendship_level",
        ),
    ]
