# Generated by Django 4.2.7 on 2024-01-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(),
        ),
    ]
