# Generated by Django 4.2.7 on 2024-01-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_notification', '0002_alter_device_token'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('user', 'token'), name='unique_user_token'),
        ),
    ]
