# Generated by Django 4.2.7 on 2024-01-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamsearchhistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='usersearchhistory',
            options={'ordering': ['-timestamp']},
        ),
    ]
