# Generated by Django 4.2.7 on 2024-02-04 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0032_alter_userprofile_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateChatParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chatroom_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PrivateChatRoom",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("last_msg", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "participants",
                    models.ManyToManyField(
                        through="chat.PrivateChatParticipant", to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrivateMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                ("timestamp", models.DateField(auto_now_add=True)),
                (
                    "chatroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.privatechatroom",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="privatechatparticipant",
            name="chatroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.privatechatroom",
            ),
        ),
        migrations.AddField(
            model_name="privatechatparticipant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.user",
            ),
        ),
    ]
