# Generated by Django 4.2.7 on 2024-02-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0032_alter_userprofile_visibility"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="privatechatroom",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="privatemessage",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterField(
            model_name="privatechatroom",
            name="last_msg",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="privatechatroom",
            name="participants",
            field=models.ManyToManyField(
                related_name="private_chat_rooms",
                through="chat.PrivateChatParticipant",
                to="user.user",
            ),
        ),
    ]
