# Generated by Django 4.2.7 on 2024-02-04 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0032_alter_userprofile_visibility"),
        ("team", "0018_teammembers_unique_user_team"),
        ("chat", "0002_alter_privatechatroom_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InquiryChatRoom",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("last_msg", models.CharField(default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inquirer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquirer_chat_rooms",
                        to="user.user",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responder_chat_rooms",
                        to="user.user",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry_chat_rooms",
                        to="team.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AlterField(
            model_name="privatechatparticipant",
            name="chatroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chat.privatechatroom"
            ),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="chatroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chat.privatechatroom"
            ),
        ),
        migrations.CreateModel(
            name="InquiryMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("T", "team"), ("I", "inquirer")], max_length=1
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                ("timestamp", models.DateField(auto_now_add=True)),
                (
                    "chatroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.inquirychatroom",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
