# Generated by Django 4.2.7 on 2024-02-04 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0032_alter_userprofile_visibility"),
        ("chat", "0003_inquirychatroom_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inquirychatroom",
            name="responder",
        ),
        migrations.AddField(
            model_name="inquirychatroom",
            name="type",
            field=models.CharField(
                choices=[("T", "team"), ("I", "inquirer")], default="T", max_length=1
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inquirychatroom",
            name="inquirer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inquiry_chat_rooms",
                to="user.user",
            ),
        ),
    ]
