# Generated by Django 4.2.7 on 2024-02-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_remove_inquirychatroom_responder_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inquirychatroom",
            name="type",
        ),
    ]
