# Generated by Django 4.2.7 on 2024-02-05 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_teamchatparticipant_teamchatroom_teammessage_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teamchatparticipant",
            old_name="team_chat",
            new_name="chatroom",
        ),
    ]
