# Generated by Django 4.2.7 on 2024-02-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_rename_team_chat_teamchatparticipant_chatroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamchatroom",
            name="background",
            field=models.CharField(default="", max_length=10),
        ),
    ]
