# Generated by Django 4.2.7 on 2024-02-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_teamchatroom_background"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamchatroom",
            name="background",
            field=models.CharField(default="0xff00FFD1", max_length=10),
        ),
    ]
