# Generated by Django 4.2.7 on 2024-02-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_alter_teamchatparticipant_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirychatroom",
            name="inquirer_unread_cnt",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inquirychatroom",
            name="responder_unread_cnt",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="privatechatparticipant",
            name="unread_cnt",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamchatparticipant",
            name="is_online",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="teamchatparticipant",
            name="last_read_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="teamchatparticipant",
            name="unread_cnt",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
