# Generated by Django 4.2.7 on 2024-02-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_inquirychatroom_inquirer_unread_cnt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirychatroom",
            name="inquirer_alarm_on",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="inquirychatroom",
            name="responder_alarm_on",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="privatechatparticipant",
            name="alarm_on",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="teamchatparticipant",
            name="alarm_on",
            field=models.BooleanField(default=True),
        ),
    ]
