# Generated by Django 4.2.7 on 2024-02-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_alter_inquirychatroom_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammessage",
            name="is_msg",
            field=models.BooleanField(default=False),
        ),
    ]
