# Generated by Django 4.2.7 on 2024-02-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_teammessage_is_msg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammessage",
            name="is_msg",
            field=models.BooleanField(default=True),
        ),
    ]
