# Generated by Django 4.2.7 on 2024-02-16 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0019_teampermission"),
        ("chat", "0016_alter_teammessage_is_msg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatemessage",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chat.privatechatparticipant",
            ),
        ),
        migrations.AlterField(
            model_name="teamchatroom",
            name="last_msg",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="teammessage",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="team.teammembers",
            ),
        ),
    ]
