# Generated by Django 4.2.7 on 2024-02-16 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0032_alter_userprofile_visibility"),
        ("chat", "0017_alter_privatemessage_sender_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teammessage",
            old_name="sender",
            new_name="member",
        ),
        migrations.AddField(
            model_name="teammessage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.user",
            ),
        ),
    ]
