# Generated by Django 4.2.7 on 2024-02-18 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0019_teampermission"),
        ("user", "0032_alter_userprofile_visibility"),
        ("chat", "0018_rename_sender_teammessage_member_teammessage_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatechatparticipant",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="privatechatparticipant",
            name="last_read_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="is_msg",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="inquirychatroom",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inquiry_chat_rooms",
                to="team.team",
            ),
        ),
        migrations.AlterField(
            model_name="privatechatroom",
            name="last_msg",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="chatroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.privatechatroom",
            ),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.user",
            ),
        ),
    ]
