# Generated by Django 4.2.7 on 2024-02-19 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0032_alter_userprofile_visibility"),
        ("chat", "0019_privatechatparticipant_is_online_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatechatparticipant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
            ),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
