# Generated by Django 4.2.7 on 2024-02-19 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0019_teampermission"),
        ("user", "0032_alter_userprofile_visibility"),
        ("chat", "0020_alter_privatechatparticipant_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inquirymessage",
            name="type",
        ),
        migrations.AddField(
            model_name="inquirychatroom",
            name="inquirer_is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inquirychatroom",
            name="inquirer_last_read_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 2, 19, 14, 23, 38, 461128, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inquirychatroom",
            name="responder_is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inquirychatroom",
            name="responder_last_read_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 2, 19, 14, 23, 52, 890999, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inquirymessage",
            name="sender",
            field=models.CharField(
                blank=True,
                choices=[("T", "team"), ("I", "inquirer")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inquirymessage",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="team.team",
            ),
        ),
        migrations.AddField(
            model_name="inquirymessage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.user",
            ),
        ),
        migrations.AlterField(
            model_name="inquirymessage",
            name="chatroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.inquirychatroom",
            ),
        ),
    ]
