# Generated by Django 4.2.7 on 2024-02-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0021_remove_inquirymessage_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirymessage",
            name="is_msg",
            field=models.BooleanField(default=True),
        ),
    ]
