# Generated by Django 4.2.7 on 2024-02-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0023_alter_inquirymessage_timestamp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teamchatroom",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.RemoveField(
            model_name="privatechatparticipant",
            name="chatroom_name",
        ),
        migrations.AddField(
            model_name="privatechatparticipant",
            name="custom_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
