# Generated by Django 4.2.7 on 2024-02-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0024_alter_teamchatroom_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inquirychatroom",
            name="inquirer_last_read_time",
        ),
        migrations.RemoveField(
            model_name="inquirychatroom",
            name="responder_last_read_time",
        ),
    ]
