# Generated by Django 4.2.7 on 2024-02-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0025_remove_inquirychatroom_inquirer_last_read_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamchatroom",
            name="last_msg",
            field=models.CharField(default="", max_length=255),
        ),
    ]
