# Generated by Django 4.2.7 on 2024-04-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0026_alter_teamchatroom_last_msg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatechatparticipant",
            name="custom_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="teamchatroom",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
