# Generated by Django 4.2.7 on 2024-05-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0026_alter_teamchatroom_last_msg"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamchatparticipant",
            name="entered_chatroom_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
