# Generated by Django 4.2.7 on 2024-06-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0027_teamchatparticipant_entered_chatroom_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamchatparticipant",
            name="entered_chatroom_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
