# Generated by Django 4.2.7 on 2024-06-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0028_alter_teamchatparticipant_entered_chatroom_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatechatroom",
            name="last_msg",
            field=models.CharField(default="", max_length=255),
        ),
    ]
