# Generated by Django 4.2.7 on 2024-06-13 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0029_alter_privatechatroom_last_msg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inquirychatroom",
            name="inquirer_alarm_on",
        ),
        migrations.RemoveField(
            model_name="inquirychatroom",
            name="inquirer_is_online",
        ),
        migrations.RemoveField(
            model_name="inquirychatroom",
            name="inquirer_unread_cnt",
        ),
        migrations.RemoveField(
            model_name="inquirychatroom",
            name="responder_alarm_on",
        ),
        migrations.RemoveField(
            model_name="inquirychatroom",
            name="responder_is_online",
        ),
        migrations.RemoveField(
            model_name="inquirychatroom",
            name="responder_unread_cnt",
        ),
        migrations.RemoveField(
            model_name="inquirymessage",
            name="team",
        ),
        migrations.RemoveField(
            model_name="inquirymessage",
            name="user",
        ),
        migrations.CreateModel(
            name="InquiryChatParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_inquirer", models.BooleanField()),
                ("unread_cnt", models.PositiveIntegerField(default=0)),
                ("alarm_on", models.BooleanField(default=True)),
                ("is_online", models.BooleanField(default=False)),
                ("last_read_time", models.DateTimeField(auto_now=True)),
                (
                    "chatroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="chat.inquirychatroom",
                    ),
                ),
            ],
        ),
    ]
