# Generated by Django 4.2.7 on 2024-06-22 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0026_alter_team_creator_alter_teammembers_custom_name_and_more"),
        ("user", "0044_remove_userexperience_end_date_and_more"),
        ("chat", "0030_remove_inquirychatroom_inquirer_alarm_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamchatparticipant",
            name="member",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="team.teammembers",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="teamchatparticipant",
            name="user",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
            preserve_default=False,
        ),
    ]
