# Generated by Django 4.2.7 on 2024-06-22 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0044_remove_userexperience_end_date_and_more"),
        ("chat", "0031_alter_teamchatparticipant_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatechatroom",
            name="user1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="private_chatrooms_1",
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="privatechatroom",
            name="user2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="private_chatrooms_2",
                to="user.user",
            ),
        ),
    ]
