# Generated by Django 4.2.7 on 2024-06-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0032_privatechatroom_user1_privatechatroom_user2"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="privatechatroom",
            constraint=models.UniqueConstraint(
                fields=("user1", "user2"), name="unique_private_chat_participant"
            ),
        ),
    ]
