# Generated by Django 4.2.7 on 2024-06-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0035_inquirychatparticipant_entered_chatroom_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="privatechatroom",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="privatechatroom",
            name="unique_private_chat_participant",
        ),
        migrations.AddConstraint(
            model_name="inquirychatparticipant",
            constraint=models.UniqueConstraint(
                fields=("chatroom", "is_inquirer"),
                name="unique_inquiry_chat_participant",
            ),
        ),
        migrations.AddConstraint(
            model_name="privatechatparticipant",
            constraint=models.UniqueConstraint(
                fields=("chatroom", "user"), name="unique_private_chat_participant"
            ),
        ),
    ]
