# Generated by Django 4.2.7 on 2023-12-06 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("team", "0009_teamlike"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
                (
                    "likes",
                    models.ManyToManyField(related_name="likes", to="team.teammembers"),
                ),
                (
                    "post_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="team.team"
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="team.teammembers",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamPostComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.CharField()),
                (
                    "comment_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="post.teampost"
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="team.teammembers",
                    ),
                ),
            ],
        ),
    ]
