# Generated by Django 4.2.7 on 2023-12-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0009_teamlike"),
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teampost",
            name="post_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="team.team",
            ),
        ),
        migrations.AlterField(
            model_name="teampost",
            name="writer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="written_posts",
                to="team.teammembers",
            ),
        ),
        migrations.AlterField(
            model_name="teampostcomment",
            name="comment_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="post.teampost",
            ),
        ),
        migrations.AlterField(
            model_name="teampostcomment",
            name="writer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="written_comments",
                to="team.teammembers",
            ),
        ),
    ]
