# Generated by Django 4.2.7 on 2023-12-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_remove_team_img_alter_team_image'),
        ('post', '0002_alter_teampost_post_to_alter_teampost_writer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teampost',
            name='likes',
        ),
        migrations.AddField(
            model_name='teampost',
            name='viewed',
            field=models.ManyToManyField(related_name='viewed_posts', to='team.teammembers'),
        ),
    ]
