# Generated by Django 4.2.7 on 2024-01-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_teampost_options_alter_teampostcomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teampostcomment',
            options={'ordering': ['created_at']},
        ),
    ]
