# Generated by Django 4.2.7 on 2024-05-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_alter_teampostcomment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teampost",
            options={"get_latest_by": "-created_at", "ordering": ["-created_at"]},
        ),
    ]
