# Generated by Django 4.2.7 on 2024-06-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_alter_teampost_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teampost",
            options={"get_latest_by": "created_at", "ordering": ["-created_at"]},
        ),
    ]
