# Generated by Django 4.2.7 on 2023-11-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interest", "0001_initial"),
        ("position", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20, unique=True)),
                ("avatar", models.JSONField(default=dict)),
                ("notifications", models.BooleanField(default=False)),
                (
                    "interests",
                    models.ManyToManyField(
                        related_name="users", to="interest.interest"
                    ),
                ),
                (
                    "positions",
                    models.ManyToManyField(
                        related_name="users", to="position.position"
                    ),
                ),
            ],
        ),
    ]
