# Generated by Django 4.2.7 on 2023-11-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("region", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "visibility",
                    models.CharField(
                        choices=[("PU", "전체 공개"), ("PI", "비공개"), ("FO", "팔로우 공개")],
                        default="PI",
                        max_length=2,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="user.user",
                    ),
                ),
                ("birthdate", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("F", "여자"), ("M", "남자"), ("U", "선택하지 않을래요")],
                        default="U",
                        max_length=1,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ALL", "전체"),
                            ("PRO", "프로젝트"),
                            ("CMP", "서포터즈/공모전"),
                            ("CLB", "동아리/학회"),
                            ("STU", "창업"),
                            ("STY", "스터디"),
                        ],
                        default="ALL",
                        max_length=3,
                    ),
                ),
                ("education", models.JSONField(default=None)),
                ("keywords", models.CharField(default=None)),
                ("tools", models.CharField(default=None)),
                ("experiences", models.JSONField(default=None)),
                ("certificates", models.CharField(default=None)),
                ("links", models.JSONField(default=None)),
                ("short_pr", models.CharField(max_length=50)),
                (
                    "city_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="region.city"
                    ),
                ),
                (
                    "province_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="region.province",
                    ),
                ),
            ],
        ),
    ]
