# Generated by Django 4.2.7 on 2023-11-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="birthdate",
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="short_pr",
            field=models.CharField(default="", max_length=50),
        ),
    ]
