# Generated by Django 4.2.7 on 2023-11-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_userprofile_birthdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="birthdate",
            field=models.CharField(default="19000101", max_length=8),
        ),
    ]
