# Generated by Django 4.2.7 on 2023-11-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_userprofile_birthdate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="city_id",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="province_id",
            new_name="province",
        ),
    ]
