# Generated by Django 4.2.7 on 2023-11-25 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("region", "0001_initial"),
        ("user", "0005_rename_city_id_userprofile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="certificates",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="region.city"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="education",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="experiences",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="keywords",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="links",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="province",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="region.province",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tools",
            field=models.CharField(default=""),
        ),
    ]
