# Generated by Django 4.2.7 on 2023-11-25 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("region", "0001_initial"),
        ("activity", "0001_initial"),
        ("user", "0007_alter_userprofile_education_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="activity",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="activity.activity",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="region.city"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="province",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="region.province",
            ),
        ),
    ]
