# Generated by Django 4.2.7 on 2023-11-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_remove_userprofile_activity_userprofile_activities"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="category",
        ),
    ]
