# Generated by Django 4.2.7 on 2023-11-30 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("region", "0001_initial"),
        ("user", "0010_remove_userprofile_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="province",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="cities",
            field=models.ManyToManyField(related_name="users", to="region.city"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="profile",
                serialize=False,
                to="user.user",
            ),
        ),
    ]
