# Generated by Django 4.2.7 on 2023-12-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_remove_userprofile_city_remove_userprofile_province_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="education",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="experiences",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="links",
            field=models.CharField(default=""),
        ),
    ]
