# Generated by Django 4.2.7 on 2023-12-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_user_background_alter_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="notifications",
        ),
    ]
