# Generated by Django 4.2.7 on 2023-12-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="friends",
            field=models.ManyToManyField(to="user.userprofile"),
        ),
    ]
