# Generated by Django 4.2.7 on 2023-12-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_userlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/1.png', upload_to='avatars/'),
        ),
    ]
