# Generated by Django 4.2.7 on 2023-12-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.URLField(),
        ),
    ]
