# Generated by Django 4.2.7 on 2023-12-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.ImageField(default='backgrounds/bg1.png', upload_to='backgrounds/'),
        ),
    ]
