# Generated by Django 4.2.7 on 2023-12-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_user_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthdate',
            field=models.CharField(default='19000101', max_length=10),
        ),
    ]
