# Generated by Django 4.2.7 on 2023-12-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_userprofile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthdate',
            field=models.CharField(default='1900-01-01', max_length=10),
        ),
    ]
