# Generated by Django 4.2.7 on 2023-12-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_alter_team_creator'),
        ('user', '0028_alter_userprofile_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_teams',
            field=models.ManyToManyField(related_name='blocked_by', to='team.team'),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(to='user.user'),
        ),
    ]
