# Generated by Django 4.2.7 on 2024-01-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0030_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uid",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="visibility",
            field=models.CharField(
                choices=[("PU", "전체 공개"), ("PI", "비공개"), ("FO", "팔로우 공개")],
                default="PU",
                max_length=2,
            ),
        ),
    ]
