# Generated by Django 4.2.7 on 2024-02-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0032_alter_userprofile_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
