# Generated by Django 4.2.7 on 2024-04-10 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0033_user_last_login_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="user",
            name="positions",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="activities",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="cities",
        ),
    ]
