# Generated by Django 4.2.7 on 2024-04-10 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0001_initial"),
        ("interest", "0001_initial"),
        ("region", "0002_alter_city_province"),
        ("position", "0001_initial"),
        ("user", "0034_remove_user_interests_remove_user_positions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(2, "Low"), (1, "Medium"), (0, "High")]
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="position.position",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(2, "Low"), (1, "Medium"), (0, "High")]
                    ),
                ),
                (
                    "interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interest.interest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(2, "Low"), (1, "Medium"), (0, "High")]
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="region.city"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(2, "Low"), (1, "Medium"), (0, "High")]
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activity.activity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="interests",
            field=models.ManyToManyField(
                related_name="users",
                through="user.UserInterest",
                to="interest.interest",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="positions",
            field=models.ManyToManyField(
                related_name="users",
                through="user.UserPosition",
                to="position.position",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="activities",
            field=models.ManyToManyField(
                related_name="users",
                through="user.UserActivity",
                to="activity.activity",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="cities",
            field=models.ManyToManyField(
                related_name="users", through="user.UserCity", to="region.city"
            ),
        ),
    ]
