# Generated by Django 4.2.7 on 2024-04-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0036_remove_userprofile_experiences_user_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userexperience",
            name="end_date",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="userexperience",
            name="start_date",
            field=models.CharField(max_length=10),
        ),
    ]
