# Generated by Django 4.2.7 on 2024-04-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0038_alter_userinterest_options_and_more"),
        ("user", "0038_remove_userprofile_links_userexternallink"),
    ]

    operations = []
