# Generated by Django 4.2.7 on 2024-04-17 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0039_merge_20240418_0125"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userexternallink",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="userexternallink",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="user.userprofile",
            ),
        ),
    ]
