# Generated by Django 4.2.7 on 2024-04-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0040_rename_name_userexternallink_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="visibility",
        ),
        migrations.AlterField(
            model_name="userexternallink",
            name="title",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="certificates",
            field=models.TextField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="keywords",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tools",
            field=models.CharField(blank=True, default="", max_length=70),
        ),
    ]
