# Generated by Django 4.2.7 on 2024-05-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0042_tool"),
    ]

    operations = [
        migrations.AddField(
            model_name="userexperience",
            name="start_end_date",
            field=models.CharField(default="", max_length=23),
        ),
    ]
