# Generated by Django 4.2.7 on 2024-05-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0043_userexperience_start_end_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userexperience",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="userexperience",
            name="start_date",
        ),
    ]
