# Generated by Django 4.2.7 on 2024-06-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0044_remove_userexperience_end_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tool",
            options={},
        ),
    ]
