# Generated by Django 4.2.7 on 2024-06-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0045_alter_tool_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tool",
            options={"managed": False},
        ),
    ]
