# Generated by Django 4.2.7 on 2023-12-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("region", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="region.province",
            ),
        ),
    ]
