# Generated by Django 4.2.7 on 2024-04-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("region", "0002_alter_city_province"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
