# Generated by Django 4.2.7 on 2023-12-03 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_userprofile_friends"),
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="to_user",
            field=models.ForeignKey(
                default=55,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="user.user",
            ),
        ),
    ]
