# Generated by Django 4.2.7 on 2023-12-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_notification_is_read_notification_to_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(max_length=30),
        ),
    ]
