# Generated by Django 4.2.7 on 2023-12-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0004_teamnotification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamnotification",
            name="is_read",
        ),
    ]
