# Generated by Django 4.2.7 on 2023-12-22 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0016_alter_team_creator'),
        ('user', '0029_user_blocked_teams_user_blocked_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_type', models.CharField(choices=[('user', 'User'), ('team', 'Team')], max_length=4)),
                ('reason', models.CharField(choices=[('inappropriate_content', '욕설/혐오 발언'), ('harassment', '성적인 수치심'), ('religious/political', '특정 종교/정치적 목적'), ('impersonation/fraud', '사칭/사기')], max_length=21)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='team.team')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='user.user')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
