# Generated by Django 4.2.7 on 2024-03-26 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0033_user_last_login_time"),
        ("team", "0023_alter_teammembers_custom_name"),
        ("review", "0003_userreview_activity_alter_userreview_content_and_more"),
        ("post", "0005_alter_teampostcomment_options"),
        ("report", "0002_report_reported_team_post_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamPostCommentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            (1, "욕설/혐오 발언"),
                            (2, "성적인 수치심"),
                            (3, "특정 종교/정치적 목적"),
                            (4, "사칭/사기"),
                        ],
                        max_length=21,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reported",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post.teampostcomment",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamPostReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            (1, "욕설/혐오 발언"),
                            (2, "성적인 수치심"),
                            (3, "특정 종교/정치적 목적"),
                            (4, "사칭/사기"),
                        ],
                        max_length=21,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reported",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="post.teampost"
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            (1, "욕설/혐오 발언"),
                            (2, "성적인 수치심"),
                            (3, "특정 종교/정치적 목적"),
                            (4, "사칭/사기"),
                        ],
                        max_length=21,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reported",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="team.team"
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            (1, "욕설/혐오 발언"),
                            (2, "성적인 수치심"),
                            (3, "특정 종교/정치적 목적"),
                            (4, "사칭/사기"),
                        ],
                        max_length=21,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reported",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_reports",
                        to="user.user",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="written_user_reports",
                        to="user.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserReviewCommentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reported_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("team", "Team"),
                            ("team_post", "TeamPost"),
                            ("team_post_comment", "TeamPostComment"),
                        ],
                        max_length=17,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("inappropriate_content", "욕설/혐오 발언"),
                            ("harassment", "성적인 수치심"),
                            ("religious/political", "특정 종교/정치적 목적"),
                            ("impersonation/fraud", "사칭/사기"),
                        ],
                        max_length=21,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reported",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="review.userreviewcomment",
                    ),
                ),
                (
                    "reported_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="team.team",
                    ),
                ),
                (
                    "reported_team_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="post.teampost",
                    ),
                ),
                (
                    "reported_team_post_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="post.teampostcomment",
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="user.user",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserReviewReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            (1, "욕설/혐오 발언"),
                            (2, "성적인 수치심"),
                            (3, "특정 종교/정치적 목적"),
                            (4, "사칭/사기"),
                        ],
                        max_length=21,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reported",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="review.userreview",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Report",
        ),
    ]
