# Generated by Django 4.2.7 on 2024-04-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0003_teampostcommentreport_teampostreport_teamreport_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userreviewcommentreport",
            name="reported_team",
        ),
        migrations.RemoveField(
            model_name="userreviewcommentreport",
            name="reported_team_post",
        ),
        migrations.RemoveField(
            model_name="userreviewcommentreport",
            name="reported_team_post_comment",
        ),
        migrations.RemoveField(
            model_name="userreviewcommentreport",
            name="reported_type",
        ),
        migrations.RemoveField(
            model_name="userreviewcommentreport",
            name="reported_user",
        ),
        migrations.AlterField(
            model_name="userreviewcommentreport",
            name="reason",
            field=models.CharField(
                choices=[
                    (1, "욕설/혐오 발언"),
                    (2, "성적인 수치심"),
                    (3, "특정 종교/정치적 목적"),
                    (4, "사칭/사기"),
                ],
                max_length=21,
            ),
        ),
    ]
