# Generated by Django 4.2.7 on 2024-01-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_eventarticle_background_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventarticle',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
    ]
