# Generated by Django 4.2.7 on 2023-12-01 15:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0013_alter_userprofile_certificates_and_more"),
        ("position", "0001_initial"),
        ("region", "0001_initial"),
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("short_pr", models.CharField(max_length=50)),
                (
                    "meet_preference",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("long_pr", models.TextField(default="")),
                (
                    "active_startdate",
                    models.CharField(default="19000101", max_length=8),
                ),
                ("active_enddate", models.CharField(default="19000102", max_length=8)),
                (
                    "recruit_startdate",
                    models.CharField(default="19000101", max_length=8),
                ),
                ("recruit_enddate", models.CharField(default="19000101", max_length=8)),
                (
                    "activity",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team",
                        to="activity.activity",
                    ),
                ),
                (
                    "cities",
                    models.ManyToManyField(related_name="team", to="region.city"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamPositions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cnt",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(3000),
                        ]
                    ),
                ),
                ("pr", models.CharField(blank=True, default="")),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="position.position",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="team.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("background", models.CharField(default="")),
                ("avatar", models.CharField(default="")),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="team.team"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="teams", through="team.TeamMembers", to="user.user"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="positions",
            field=models.ManyToManyField(
                related_name="teams",
                through="team.TeamPositions",
                to="position.position",
            ),
        ),
    ]
