# Generated by Django 4.2.7 on 2023-12-03 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("position", "0001_initial"),
        ("user", "0014_friendrequest"),
        ("team", "0003_team_keywords"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammembers",
            name="avatar",
        ),
        migrations.AddField(
            model_name="team",
            name="creator",
            field=models.ForeignKey(
                default=54, on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
        ),
        migrations.AlterField(
            model_name="teampositions",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="TeamApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="user.user",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="position.position",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="team.team",
                    ),
                ),
            ],
        ),
    ]
