# Generated by Django 4.2.7 on 2023-12-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0005_teamapplication_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamapplication",
            name="accepted",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
