# Generated by Django 4.2.7 on 2023-12-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0007_alter_team_active_enddate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="image",
            field=models.CharField(default=""),
        ),
    ]
