# Generated by Django 4.2.7 on 2023-12-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("interest", "0001_initial"),
        ("team", "0009_teamlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="interest",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interest",
                to="interest.interest",
            ),
        ),
    ]
