# Generated by Django 4.2.7 on 2023-12-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0010_team_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammembers",
            name="noti_unread_cnt",
            field=models.IntegerField(default=0),
        ),
    ]
