# Generated by Django 4.2.7 on 2023-12-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_teammembers_noti_unread_cnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='recruit_enddate',
        ),
    ]
