# Generated by Django 4.2.7 on 2023-12-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_remove_team_recruit_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='recruit_enddate',
            field=models.CharField(default='2024-01-02', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='active_enddate',
            field=models.CharField(default='2024-01-02', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='active_startdate',
            field=models.CharField(default='2024-01-01', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='recruit_startdate',
            field=models.CharField(default='2024-01-01', max_length=10),
        ),
    ]
