# Generated by Django 4.2.7 on 2023-12-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_team_recruit_enddate_alter_team_active_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.ImageField(default='teams/default.png', upload_to='teams/'),
        ),
    ]
