# Generated by Django 4.2.7 on 2023-12-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_team_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='img',
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default='teams/default.png', upload_to='teams/'),
        ),
    ]
