# Generated by Django 4.2.7 on 2023-12-21 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_userprofile_birthdate'),
        ('team', '0015_remove_team_img_alter_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(default=54, on_delete=django.db.models.deletion.CASCADE, related_name='created_teams', to='user.user'),
        ),
    ]
