# Generated by Django 4.2.7 on 2024-02-04 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0032_alter_userprofile_visibility"),
        ("team", "0018_teammembers_unique_user_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responder",
                        to="user.user",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission",
                        to="team.team",
                    ),
                ),
            ],
        ),
    ]
