# Generated by Django 4.2.7 on 2024-02-20 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0019_teampermission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teampermission",
            name="id",
        ),
        migrations.AlterField(
            model_name="teampermission",
            name="team",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="permission",
                serialize=False,
                to="team.team",
            ),
        ),
    ]
