# Generated by Django 4.2.7 on 2024-02-23 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0032_alter_userprofile_visibility"),
        ("team", "0020_remove_teampermission_id_alter_teampermission_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teampermission",
            name="responder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responder",
                to="user.user",
            ),
        ),
    ]
