# Generated by Django 4.2.7 on 2024-03-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0021_alter_teampermission_responder"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammembers",
            name="custom_name",
            field=models.CharField(default=""),
        ),
    ]
