# Generated by Django 4.2.7 on 2024-04-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0022_teammembers_custom_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammembers",
            name="custom_name",
            field=models.CharField(default="", max_length=20),
        ),
    ]
