# Generated by Django 4.2.7 on 2024-06-19 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0044_remove_userexperience_end_date_and_more"),
        ("team", "0025_teamapplication_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_teams",
                to="user.user",
            ),
        ),
        migrations.AlterField(
            model_name="teammembers",
            name="custom_name",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="teampermission",
            name="responder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responder",
                to="user.user",
            ),
        ),
    ]
