# Generated by Django 4.2.7 on 2024-03-14 15:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import review.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0033_user_last_login_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReview",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "star_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=0,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                            review.models.validate_0_5_increment,
                        ],
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, default="", max_length=300, null=True),
                ),
                ("edited", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserReviewKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(default="", max_length=20)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "Activity"), (1, "Positive"), (2, "Negative")]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserReviewComment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(default="", max_length=300)),
                ("edited", models.BooleanField(default=False)),
                (
                    "review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_review",
                        to="review.userreview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userreview",
            name="keywords",
            field=models.ManyToManyField(
                related_name="users", to="review.userreviewkeyword"
            ),
        ),
        migrations.AddField(
            model_name="userreview",
            name="reviewee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="userreview",
            name="reviewer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="written_reviews",
                to="user.user",
            ),
        ),
    ]
