# Generated by Django 4.2.7 on 2024-03-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userreviewcomment",
            name="user",
        ),
        migrations.AlterField(
            model_name="userreviewcomment",
            name="review",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="review.userreview",
            ),
        ),
    ]
