# Generated by Django 4.2.7 on 2024-03-22 14:08

import django.core.validators
from django.db import migrations, models
import review.models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_remove_userreviewcomment_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreview",
            name="activity",
            field=models.IntegerField(
                choices=[
                    (1, "프로젝트"),
                    (2, "서브터즈/공모전"),
                    (3, "동아리/학회"),
                    (4, "창업"),
                    (5, "스터디"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userreview",
            name="content",
            field=models.TextField(default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="userreview",
            name="star_rating",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                    review.models.validate_0_5_increment,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userreviewkeyword",
            name="type",
            field=models.IntegerField(choices=[(1, "Positive"), (2, "Negative")]),
        ),
    ]
