# Generated by Django 4.2.7 on 2024-04-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0003_userreview_activity_alter_userreview_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreview",
            name="content",
            field=models.TextField(blank=True, default="", max_length=300),
        ),
    ]
