# Generated by Django 4.2.7 on 2024-04-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_alter_userreview_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreviewcomment",
            name="content",
            field=models.TextField(default="", max_length=200),
        ),
    ]
