# Generated by Django 4.2.7 on 2024-04-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0005_alter_userreviewcomment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreview",
            name="keywords",
            field=models.ManyToManyField(
                related_name="reviews", to="review.userreviewkeyword"
            ),
        ),
    ]
