# Generated by Django 4.2.7 on 2024-06-13 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0001_initial"),
        ("review", "0006_alter_userreview_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreview",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="activity.activity"
            ),
        ),
    ]
