# Generated by Django 4.2.7 on 2024-06-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0007_alter_userreview_activity"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userreview",
            constraint=models.UniqueConstraint(
                fields=("reviewee", "reviewer"), name="unique_reviewee_reviewer"
            ),
        ),
    ]
