# Generated by Django 4.2.7 on 2023-11-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=10, unique=True)),
                ("total_cnt", models.IntegerField(default=0)),
                ("recent_cnt", models.IntegerField(default=0)),
            ],
        ),
    ]
