# Generated by Django 4.2.7 on 2024-05-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interest", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interest",
            name="recent_cnt",
        ),
        migrations.RemoveField(
            model_name="interest",
            name="total_cnt",
        ),
        migrations.AddField(
            model_name="interest",
            name="category",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "IT related"),
                    (2, "media related"),
                    (3, "leiure related"),
                    (4, "beatuy related"),
                    (5, "environment related"),
                    (0, "other related"),
                ],
                default=0,
            ),
        ),
    ]
