# Generated by Django 4.2.7 on 2024-04-14 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0037_alter_userexperience_end_date_and_more"),
        ("interest", "0001_initial"),
        ("position", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileCard",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="user.user",
                        verbose_name="profile_card",
                    ),
                ),
                ("background", models.PositiveSmallIntegerField(default=0)),
                ("badge_background", models.PositiveSmallIntegerField(default=0)),
                ("badge_one", models.ImageField(blank=True, null=True, upload_to="")),
                ("badge_two", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interest.interest",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="position.position",
                    ),
                ),
            ],
        ),
    ]
