# Generated by Django 4.2.7 on 2024-04-14 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0037_alter_userexperience_end_date_and_more"),
        ("profile_card", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profilecard",
            old_name="background",
            new_name="badge_bg_idx",
        ),
        migrations.RenameField(
            model_name="profilecard",
            old_name="badge_background",
            new_name="bg_idx",
        ),
        migrations.AlterField(
            model_name="profilecard",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="profile_card",
                serialize=False,
                to="user.user",
                verbose_name="profile_card",
            ),
        ),
    ]
