# Generated by Django 4.2.7 on 2024-04-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_card", "0002_rename_background_profilecard_badge_bg_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilecard",
            name="badge_one",
            field=models.ImageField(default="", upload_to=""),
        ),
        migrations.AlterField(
            model_name="profilecard",
            name="badge_two",
            field=models.ImageField(default="", upload_to=""),
        ),
    ]
