# Generated by Django 4.2.7 on 2024-04-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_card", "0004_alter_profilecard_interest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilecard",
            name="interest",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "Low"), (1, "Medium"), (0, "High")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="profilecard",
            name="position",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "Low"), (1, "Medium"), (0, "High")], default=0
            ),
        ),
    ]
